name: backend-dev-cd.yml

on:
  push:
    branches: [ "jin409" ]

jobs:
  build:
    runs-on: [ self-hosted, linux, ARM64 ]
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Grant execute permission to gradlew
        run: chmod +x gradlew

      - name: Build project
        run: ./gradlew clean build -x test

      - name: Update .env file
        run: |
          cat > /home/ubuntu/lv3-final-mission/.env <<EOF
          DEV_DATASOURCE_URL=${{ secrets.DEV_DATASOURCE_URL }}
          DEV_DATASOURCE_USERNAME=${{ secrets.DEV_DATASOURCE_USERNAME }}
          DEV_DATASOURCE_PASSWORD=${{ secrets.DEV_DATASOURCE_PASSWORD }}
          NAME_GENERATOR_API_KEY=${{ secrets.NAME_GENERATOR_API_KEY }}
          TOKEN_SECRET_KEY=${{ secrets.TOKEN_SECRET_KEY }}
          ACTIVE_PROFILE=dev
          EOF

      - name: Restart service
        run: |
          sudo systemctl daemon-reload
          sudo systemctl restart lv3
          sudo systemctl status lv3 --no-pager
